[build]
command = "npm run build"
publish = ".next"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/**/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=31536000"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"